on:
  workflow_dispatch:
    inputs:
      environment:
        description: "choose environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment.."
